spring:
  datasource:
    url: jdbc:mariadb://localhost/memo
    username : root
    password : green502
mybatis:
  configuration :
#    아래는 database에서 오는 데이터에 대한 스네이크 케이스를 camel 케이스로 변경
    map-underscore-to-camel-case: true
  mapper-locations : mappers/**/*.xml